parameters:
  - name: working_directory
    default: manifests

jobs:
  - job: kubeaudit
    steps:
      - task: Bash@3
        displayName: "Install Homebrew"
        inputs:
          targetType: "inline"
          script: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/vsts/.bash_profile
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
      - task: Bash@3
        displayName: "Install kubeaudit"
        inputs:
          targetType: "inline"
          script: "/home/linuxbrew/.linuxbrew/bin/brew install kubeaudit && kubeaudit version"
      - task: Bash@3
        displayName: "kubeaudit Static Code Analysis"
        continueOnError: true
        inputs:
          targetType: "inline"
          script: |
            kubeaudit all -f ${{ parameters.working_directory }}/*.yaml --format sarif > results.sarif
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "results.sarif"
          ArtifactName: "CodeAnalysisLogs"
          publishLocation: "Container"