parameters:
  - name: working_directory
    default: manifests

jobs:
  - job: kubescape
    steps:
      - task: Bash@3
        displayName: "Install Homebrew"
        inputs:
          targetType: "inline"
          script: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/vsts/.bash_profile
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      - task: Bash@3
        displayName: "Install kubescape"
        inputs:
          targetType: "inline"
          script: "brew install kubescape"
      - task: Bash@3
        displayName: "kubescape Static Code Analysis"
        continueOnError: true
        inputs:
          targetType: "inline"
          script: |
            kubescape scan manifests/*.yaml --format sarif > results.sarif
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "results.sarif"
          ArtifactName: "CodeAnalysisLogs"
          publishLocation: "Container"