parameters:
  - name: working_directory
    default: manifests

jobs:
  - job: kubescape
    steps:
      - task: CmdLine@2
        displayName: "Install kubescape"
        inputs:
          script: |           
            curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
            kubescape version
      - task: Bash@3
        displayName: "kubescape Static Code Analysis"
        continueOnError: true
        inputs:
          targetType: "inline"
          script: |
            # kubescape scan manifests/*.yaml || true
            kubescape scan ${{ parameters.working_directory }}/*.yaml --format sarif
            cat report.sarif
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "report.sarif"
          ArtifactName: "CodeAnalysisLogs"
          publishLocation: "Container"