parameters:
  - name: working_directory
    default: manifests

jobs:
  - job: kubescape
    steps:
      - task: CmdLine@2
        displayName: "Install kubescape"
        inputs:
          script: |           
            sudo add-apt-repository ppa:kubescape/kubescape
            sudo apt update
            sudo apt install kubescape -y
            kubescape version
      - task: Bash@3
        displayName: "kubescape Static Code Analysis"
        continueOnError: true
        inputs:
          targetType: "inline"
          script: |
            kubescape scan manifests/*.yaml || true
            kubescape scan manifests/*.yaml --format sarif
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "report.sarif"
          ArtifactName: "CodeAnalysisLogs"
          publishLocation: "Container"