parameters:
  - name: working_directory
    default: manifests

jobs:
  - job: kube_score
    steps:
      - script: brew install kube-score
        displayName: "Install kube-score"
      - script: kube-score score ${{ parameters.working_directory }}/*.yaml --output-format sarif > results.sarif
        displayName: Scan manifests using kube-score
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "results.sarif"
          ArtifactName: "CodeAnalysisLogs"
          publishLocation: "Container"
