parameters:
  - name: working_directory
    default: manifests

jobs:
  - job: kubescape
    steps:
      - bash: |
          sudo rm -rf /usr/local/*
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
        condition: eq(variables['Agent.OS'], 'Linux')
      - bash: PATH=$PATH:/home/linuxbrew/.linuxbrew/bin 
      - task: Bash@3
        displayName: "Install kubescape"
        inputs:
          targetType: "inline"
          script: "/home/linuxbrew/.linuxbrew/bin/brew install kubescape && ls /home/linuxbrew/.linuxbrew/Cellar/kubescape/2.9.1"
      - task: Bash@3
        displayName: "kubescape Static Code Analysis"
        continueOnError: true
        inputs:
          targetType: "inline"
          script: |
            kubescape scan manifests/*.yaml --format sarif > results.sarif
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "results.sarif"
          ArtifactName: "CodeAnalysisLogs"
          publishLocation: "Container"