name: Kube-score Scan

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'The working directory to scan'
        type: string
        required: false
        default: 'manifests'

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    
      - name: Install kube-score
        run: |
            brew install kube-score
      - name: Scan manifests with kube-score
        run: |
            kube-score score ${{ inputs.working-directory }}/*.yaml --output-format sarif > results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: results.sarif