name: Kubescape Scan

on:
    workflow_call:
      inputs:
        working-directory:
          description: 'The working directory to scan'
          type: string
          required: false
          default: 'manifests'
jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v3
    - uses: kubescape/github-action@main
      continue-on-error: true
      with:
        files: ${{ inputs.working-directory }}
        format: sarif
        outputFile: results
    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif