name: Trivy Scan

on:
  workflow_call:
    inputs:
        working-directory:
            description: 'The working directory to scan'
            type: string
            required: false
            default: 'manifests'

jobs:
  
  scan:
    permissions:
      contents: read
      security-events: write      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
            scan-type: 'config'
            format: 'sarif'
            output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'